[buildPlans.pes-mono]
family = "Pes Mono"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.pes-mono.variants.design]
capital-c = "unilateral-inward-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "flat-hook-serifed"
capital-n = "asymmetric"
capital-q = "vertical-crossing"
capital-r = "straight-open"
capital-s = "unilateral-inward-serifed"
a = "single-storey-serifless"
c = "unilateral-inward-serifed"
f = "flat-hook-extended"
g = "single-storey-flat-hook-serifless"
i = "hooky"
j = "flat-hook-serifed"
r = "hookless"
s = "unilateral-inward-serifed"
t = "standard-short-neck"
w = "straight-flat-top"
y = "cursive-flat-hook"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-tailed"
lower-lambda = "straight-turn"
zero = "dotted-oval"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "oblique-upper-left-bar"
seven = "straight-serifed"
asterisk = "hex-low"
underscore = "low"
pilcrow = "low"
caret = "high"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "flat-top"
at = "short"
percent = "rings-continuous-slash-also-connected"
lig-ltgteq = "slanted"
question = "corner"
punctuation-dot = "square"

[buildPlans.pes-mono.ligations]
inherits = "dlig"

[buildPlans.pes-mono.weights.extralight]
shape = 200
menu = 200
css = 200

[buildPlans.pes-mono.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.pes-mono.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.pes-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"