[buildPlans.pes-mono]
family = "Pes Mono"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.pes-mono.variants.design]
capital-m = "flat-bottom"
capital-q = "vertical-crossing"
capital-w = "straight-flat-top"
a = "single-storey-serifless"
f = "extended"
g = "single-storey-serifless"
r = "hookless"
w = "straight-flat-top"
y = "cursive"
zero = "dotted-oval"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "oblique-upper-left-bar"
six = "straight-bar"
seven = "bend-serifed"
nine = "open-contour"
asterisk = "hex-low"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "flat-top"
at = "short"
question = "corner"
punctuation-dot = "round"

[buildPlans.pes-mono.ligations]
inherits = "dlig"

[buildPlans.pes-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"