[buildPlans.pes-mono]
family = "Pes Mono"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.pes-mono.variants.design]
capital-j = "flat-hook-serifed"
capital-n = "asymmetric"
capital-q = "vertical-crossing"
capital-r = "straight-open"
capital-w = "straight-vertical-sides"
a = "single-storey-serifless"
f = "extended"
r = "hookless"
w = "straight-vertical-sides"
y = "cursive"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-tailed"
lower-lambda = "straight-turn"
zero = "dotted-oval"
two = "straight-neck"
three = "flat-top"
asterisk = "hex-low"
underscore = "low"
pilcrow = "low"
caret = "high"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "flat-top"
at = "short"
percent = "rings-continuous-slash-also-connected"
lig-ltgteq = "slanted"
question = "corner"

  [buildPlans.pes-mono.ligations]
  inherits = "dlig"

[buildPlans.pes-mono.weights.extralight]
shape = 200
menu = 200
css = 200

[buildPlans.pes-mono.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.pes-mono.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.pes-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"