[buildPlans.nodens]
family = "Nodens"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.nodens.variants.design]
capital-j = "flat-hook-serifed"
capital-n = "asymmetric"
capital-q = "vertical-crossing"
a = "single-storey-serifless"
f = "flat-hook-extended"
g = "single-storey-flat-hook-serifless"
j = "flat-hook-serifed"
r = "hookless"
w = "straight-vertical-sides"
y = "cursive-flat-hook"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-descending"
zero = "dotted-oval"
two = "straight-neck"
three = "flat-top"
four = "closed"
eight = "crossing-asymmetric"
asterisk = "hex-low"
pilcrow = "low"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "flat-top"
at = "short"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"
question = "corner"

[buildPlans.nodens.ligations]
inherits = "dlig"

[buildPlans.nodens.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
