[buildPlans.pes-mono]
family = "Pes Mono"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.pes-mono.variants.design]
capital-j = "flat-hook-serifed"
capital-m = "flat-bottom"
capital-q = "vertical-crossing"
capital-w = "straight-flat-top"
a = "single-storey-serifless"
c = "serifless"
f = "flat-hook-extended"
g = "single-storey-flat-hook-serifless"
i = "hooky"
j = "flat-hook-serifed"
r = "hookless"
w = "straight-flat-top"
y = "cursive-flat-hook"
zero = "dotted-oval"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "oblique-upper-left-bar"
seven = "straight-serifed"
nine = "straight-bar"
asterisk = "hex-low"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "upper-open"
at = "fourfold"
question = "corner"
punctuation-dot = "round"

  [buildPlans.pes-mono.ligations]
  inherits = "dlig"

[buildPlans.pes-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"