[buildPlans.pes-mono]
family = "Pes Mono"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.pes-mono.variants.design]
capital-j = "flat-hook-serifed"
capital-n = "asymmetric"
capital-q = "vertical-crossing"
capital-u = "toothed"
a = "single-storey-serifless"
f = "flat-hook-extended"
g = "single-storey-flat-hook-serifless"
j = "flat-hook-serifed"
r = "hookless"
t = "standard-short-neck"
w = "straight-flat-top"
y = "cursive-flat-hook"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
zero = "dotted-oval"
one = "base"
two = "curly-neck"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "bend-serifless"
eight = "two-circles"
nine = "open-contour"
punctuation-dot = "square"
asterisk = "hex-low"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "upper-open"
percent = "rings-continuous-slash"
pilcrow = "low"
partial-derivative = "curly-bar"
lig-ltgteq = "slanted"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

  [buildPlans.pes-mono.ligations]
  inherits = "dlig"

[buildPlans.pes-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
