[buildPlans.pes-mono]
family = "Pes Mono"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.pes-mono.variants.design]
capital-q = "vertical-crossing"
capital-w = "straight-flat-top"
a = "single-storey-serifless"
f = "extended"
g = "single-storey-serifless"
i = "hooky"
r = "hookless"
w = "straight-flat-top"
y = "cursive"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-tailed"
zero = "dotted-oval"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "vertical-upper-left-bar"
six = "open-contour"
seven = "bend-serifless"
nine = "open-contour"
asterisk = "hex-low"
underscore = "low"
pilcrow = "low"
caret = "high"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "closed"
at = "short"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"
lig-ltgteq = "slanted"

[buildPlans.pes-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"