[buildPlans.Signoir]
family = "Signoir"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Signoir.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "flat-hook-serifed"
capital-q = "vertical-crossing"
capital-r = "straight-open-serifless"
a = "single-storey-serifless"
f = "flat-hook-extended"
g = "single-storey-flat-hook-serifless"
i = "hooky"
j = "flat-hook-serifed"
l = "hooky"
r = "hookless-serifless"
t = "bent-hook-short-neck2"
w = "straight-flat-top-serifless"
y = "cursive-flat-hook-serifless"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
zero = "oval-dotted"
two = "straight-neck"
four = "closed"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing"
nine = "open-contour"
asterisk = "hex-low"
at = "compact"
percent = "rings-continuous-slash"
question = "corner"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

  [buildPlans.Signoir.ligations]
  inherits = "dlig"

[buildPlans.Signoir.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Signoir.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.Signoir.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Signoir.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
