[buildPlans.pes-mono]
family = "Pes Mono"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.pes-mono.variants.design]
capital-j = "flat-hook-serifed"
capital-m = "flat-bottom-serifless"
capital-q = "vertical-crossing"
capital-w = "straight-flat-top-serifless"
a = "single-storey-serifless"
f = "flat-hook-extended-crossbar-at-x-height"
g = "single-storey-serifless"
i = "hooky"
j = "flat-hook-serifed"
r = "corner-hooked-serifless"
t = "standard-short-neck2"
w = "straight-flat-top-serifless"
y = "cursive-serifless"
lower-delta = "flat-top"
zero = "oval-dotted"
two = "straight-neck"
three = "flat-top"
four = "closed"
six = "open-contour"
seven = "bend-serifless"
eight = "two-circles"
nine = "open-contour"
diacritic-dot = "square"
punctuation-dot = "square"
asterisk = "hex-low"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "flat-top"
at = "compact"
percent = "rings-continuous-slash"
question = "corner"
lig-ltgteq = "slanted"

  [buildPlans.pes-mono.ligations]
  inherits = "dlig"

[buildPlans.pes-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
