[buildPlans.pes-mono]
family = "Pes Mono"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.pes-mono.variants.design]
capital-j = "flat-hook-serifed"
capital-q = "vertical-crossing"
capital-w = "straight-vertical-sides"
a = "single-storey-serifless"
f = "flat-hook-extended"
g = "single-storey-flat-hook-serifless"
i = "hooky"
j = "flat-hook-serifed"
r = "hookless"
w = "straight-vertical-sides"
y = "cursive-flat-hook"
zero = "dotted-oval"
two = "straight-neck"
three = "flat-top"
four = "closed"
eight = "crossing-asymmetric"
asterisk = "hex-low"
pilcrow = "low"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "flat-top"
at = "fourfold-solid-inner"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"
question = "corner-flat-hooked"

[buildPlans.pes-mono.ligations]
inherits = "dlig"

[buildPlans.pes-mono.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.pes-mono.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.pes-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"