[buildPlans.pes-mono]
family = "Pes Mono"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.pes-mono.variants.design]
capital-j = "flat-hook-serifed"
capital-m = "flat-bottom"
capital-q = "vertical-crossing"
capital-w = "straight-flat-top"
a = "single-storey-serifless"
f = "flat-hook-extended"
g = "single-storey-flat-hook-serifless"
j = "flat-hook-serifed"
r = "hookless"
w = "straight-flat-top"
y = "cursive-flat-hook"
long-s = "flat-hook-tailed"
eszet = "sulzbacher-tailed"
zero = "dotted-oval"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "bend-serifed"
nine = "open-contour"
asterisk = "hex-low"
paren = "large-contour"
brace = "curly-flat-boundary"
at = "short"

[buildPlans.pes-mono.ligations]
inherits = "dlig"

[buildPlans.pes-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"