[buildPlans.pes-term]
family = "Pes Term"
spacing = "term"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false
no-ligation = true

[buildPlans.pes-term.variants.design]
capital-j = "flat-hook-serifed"
capital-m = "flat-bottom-serifless"
capital-q = "vertical-crossing"
capital-w = "straight-flat-top-serifless"
a = "single-storey-serifless"
f = "flat-hook-extended"
g = "single-storey-flat-hook-serifless"
i = "hooky"
j = "flat-hook-serifed"
r = "hookless-serifless"
t = "standard-short-neck2"
w = "straight-flat-top-serifless"
y = "cursive-flat-hook-serifless"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
zero = "oval-dotted"
three = "flat-top"
asterisk = "hex-low"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "upper-open"
at = "compact"
percent = "rings-continuous-slash"
pilcrow = "low"
partial-derivative = "curly-bar"
lig-ltgteq = "slanted"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.pes-term.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.pes-term.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"